### ISSUE TITLE
ticking entity when I put on basic chest plate 

### ISSUE THREAD

**Issue by bear989** [Blood-Asp/gregtechextras#1]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 8/10/15 5:08 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
    at bloodasp.gregtechextras.armor.ModularArmor_Item.onArmorTick(ModularArmor_Item.java:259)
    at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:319)
    at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:538)
    at net.minecraft.client.entity.EntityPlayerSP.func_70636_d(EntityPlayerSP.java:287)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
    at net.minecraft.client.entity.EntityClientPlayerMP.func_70071_h_(SourceFile:63)
    at net.minecraft.world.World.func_72866_a(World.java:2070)
    at net.minecraft.world.World.func_72870_g(World.java:2034)
    at net.minecraft.world.World.func_72939_s(World.java:1887)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at bloodasp.gregtechextras.armor.ModularArmor_Item.onArmorTick(ModularArmor_Item.java:259)
    at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:319)
    at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:538)
    at net.minecraft.client.entity.EntityPlayerSP.func_70636_d(EntityPlayerSP.java:287)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
    at net.minecraft.client.entity.EntityClientPlayerMP.func_70071_h_(SourceFile:63)
    at net.minecraft.world.World.func_72866_a(World.java:2070)
    at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
    Entity Type: null (net.minecraft.client.entity.EntityClientPlayerMP)
    Entity ID: 54889
    Entity Name: Bear989Sr
    Entity's Exact location: 1295.43, 70.62, -159.69
    Entity's Block location: World: (1295,70,-160), Chunk: (at 15,4,0 in 80,-10; contains blocks 1280,0,-160 to 1295,255,-145), Region: (2,-1; contains chunks 64,-32 to 95,-1, blocks 1024,0,-512 to 1535,255,-1)
    Entity's Momentum: 0.00, -0.08, 0.00
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1887)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['Bear989Sr'/54889, l='MpServer', x=1295.43, y=70.62, z=-159.69]]
    Chunk stats: MultiplayerChunkCache: 5, 5
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-131,64,44), Chunk: (at 13,4,12 in -9,2; contains blocks -144,0,32 to -129,255,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 162020966 game time, 171996150 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 1 total; [EntityClientPlayerMP['Bear989Sr'/54889, l='MpServer', x=1295.43, y=70.62, z=-159.69]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_51, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 454327392 bytes (433 MB) / 1516765184 bytes (1446 MB) up to 1631584256 bytes (1556 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1750M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 53 mods loaded, 53 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJA  mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJA  FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1448-1.7.10.jar) 
    UCHIJA  Forge{10.13.4.1448} [Minecraft Forge](forge-1.7.10-10.13.4.1448-1.7.10.jar) 
    UCHIJA  CodeChickenCore{1.0.7.46} [CodeChicken Core](minecraft.jar) 
    UCHIJA  ivtoolkit{1.2} [IvToolkit](minecraft.jar) 
    UCHIJA  MobiusCore{1.2.5} [MobiusCore](minecraft.jar) 
    UCHIJA  NotEnoughItems{1.0.5.111} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
    UCHIJA  psychedelicraftcore{1.4} [Psychedelicraft Core](minecraft.jar) 
    UCHIJA  BiblioCraft{1.10.4} [BiblioCraft](BiblioCraft[v1.10.4][MC1.7.10].jar) 
    UCHIJA  gregapi{GT6-MC1710} [Greg-API](gregtech_1.7.10-6.00.50.jar) 
    UCHIJA  IC2{2.2.756-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.756-experimental.jar) 
    UCHIJA  BuildCraft|Core{7.0.19} [BuildCraft](buildcraft-7.0.19.jar) 
    UCHIJA  Forestry{3.5.7.16} [Forestry for Minecraft](forestry_1.7.10-3.5.7.16.jar) 
    UCHIJA  BiblioWoodsForestry{1.7} [BiblioWoods Forestry Edition](BiblioWoods[Forestry][v1.7].jar) 
    UCHIJA  BuildCraft|Silicon{7.0.19} [BC Silicon](buildcraft-7.0.19.jar) 
    UCHIJA  BuildCraft|Transport{7.0.19} [BC Transport](buildcraft-7.0.19.jar) 
    UCHIJA  BuildCraft|Builders{7.0.19} [BC Builders](buildcraft-7.0.19.jar) 
    UCHIJA  BuildCraft|Robotics{7.0.19} [BC Robotics](buildcraft-7.0.19.jar) 
    UCHIJA  BuildCraft|Energy{7.0.19} [BC Energy](buildcraft-7.0.19.jar) 
    UCHIJA  BuildCraft|Factory{7.0.19} [BC Factory](buildcraft-7.0.19.jar) 
    UCHIJA  BuildCraft|Compat{7.0.8} [BuildCraft Compat](buildcraft-compat-7.0.8.jar) 
    UCHIJA  CarpentersBlocks{3.3.7 DEV} [Carpenter's Blocks](Carpenter's Blocks v3.3.7 DEV - MC 1.7.10.jar) 
    UCHIJA  Railcraft{9.6.1.0} [Railcraft](Railcraft_1.7.10-9.6.1.0.jar) 
    UCHIJA  TwilightForest{2.3.7} [The Twilight Forest](twilightforest-1.7.10-2.3.7.jar) 
    UCHIJA  chisel{2.3.10.37} [Chisel 2](Chisel2-2.3.10.37.jar) 
    UCHIJA  props{2.0.2} [Decocraft](Decocraft-2.0.2_1.7.10.jar) 
    UCHIJA  DragonsRadioMod{1.6.3} [Dragon's Radio Mod](DragonsRadioMod-MC1.7.10-1.6.3.jar) 
    UCHIJA  eplus{3.0.2-d} [Enchanting Plus](EnchantingPlus-1.7.10-3.0.2-d.jar) 
    UCHIJA  ExtraUtilities{1.2.6} [Extra Utilities](extrautilities-1.2.6.jar) 
    UCHIJA  FastCraft{1.21} [FastCraft](fastcraft-1.21.jar) 
    UCHIJA  fastleafdecay{1.1} [Fast Leaf Decay](FastLeafDecay-1.7.10-1.1.jar) 
    UCHIJA  foxlib{1.7.10-0.7.0} [FoxLib](FoxLib-1.7.10-0.7.0.jar) 
    UCHIJA  GregsLighting{1.11.2} [Greg's Lighting](GregsLighting-1.11.2-mc1.7.10.jar) 
    UCHIJA  gregtech{GT6-MC1710} [GregTech](gregtech_1.7.10-6.00.50.jar) 
    UCHIJA  gtextras{0.3.2} [GTExtras](GTExtras-0.3.2.jar) 
    UCHIJA  ImmibisCore{59.1.1} [Immibis Core](immibis-core-59.1.1.jar) 
    UCHIJA  LavaMonsters{2.2.1} [Lava Monsters](LavaMonsters-1.7.10-2.2.1.jar) 
    UCHIJA  Morpheus{1.7.10-1.6.4} [Morpheus](Morpheus-1.7.10-1.6.4.jar) 
    UCHIJA  NEIAddons{1.12.10.33} [NEI Addons](neiaddons-1.12.10.33-mc1.7.10.jar) 
    UCHIJA  NEIAddons|AppEng{1.12.10.33} [NEI Addons: Applied Energistics 2](neiaddons-1.12.10.33-mc1.7.10.jar) 
    UCHIJA  NEIAddons|Botany{1.12.10.33} [NEI Addons: Botany](neiaddons-1.12.10.33-mc1.7.10.jar) 
    UCHIJA  NEIAddons|Forestry{1.12.10.33} [NEI Addons: Forestry](neiaddons-1.12.10.33-mc1.7.10.jar) 
    UCHIJA  NEIAddons|CraftingTables{1.12.10.33} [NEI Addons: Crafting Tables](neiaddons-1.12.10.33-mc1.7.10.jar) 
    UCHIJA  NEIAddons|ExNihilo{1.12.10.33} [NEI Addons: Ex Nihilo](neiaddons-1.12.10.33-mc1.7.10.jar) 
    UCHIJA  neiintegration{1.0.9} [NEI Integration](NEIIntegration-MC1.7.10-1.0.9.jar) 
    UCHIJA  ObsidiPlates{3.0.0.18} [ObsidiPlates](ObsidiPlates-1.7.10-universal-3.0.0.18.jar) 
    UCHIJA  MapWriter{2.1.2} [MapWriter](Opis-1.2.5_1.7.10.jar) 
    UCHIJA  Opis{1.2.5} [Opis](Opis-1.2.5_1.7.10.jar) 
    UCHIJA  psychedelicraft{1.5.2} [Psychedelicraft](Psychedelicraft-1.5.2.n110.jar) 
    UCHIJA  RedLogic{59.1.11} [RedLogic](redlogic-59.1.11.jar) 
    UCHIJA  SpecialMobs{3.1.1} [Special Mobs](SpecialMobs-1.7.10-3.1.1.jar) 
    UCHIJA  Tails{1.7.10-1.3.1} [Tails](Tails-1.7.10-1.3.1.jar) 
    UCHIJA  Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 353.06' Renderer: 'GeForce GT 720/PCIe/SSE2'
    Launched Version: 1.7.10-Forge10.13.4.1448-1.7.10
    LWJGL: 2.9.1
    OpenGL: GeForce GT 720/PCIe/SSE2 GL version 4.5.0 NVIDIA 353.06, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by Blood-Asp** [comment]
Missing null check. fixed for next update.
