### ISSUE TITLE
game crash at start

### ISSUE THREAD

**Issue by SirKastros** [Blood-Asp/gregtechextras#3]
updated gregtech to 6.00.59 and have gregtechextras 0.3.3 installed. and I get this crash report

---- Minecraft Crash Report ----
// Don't do that.

Time: 11/10/15 10:25 AM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: gregapi.block.multitileentity.MultiTileEntityRegistry.add(Ljava/lang/String;Ljava/lang/String;Lgregapi/block/multitileentity/MultiTileEntityClassContainer;)Lnet/minecraft/item/ItemStack;
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchMethodError: gregapi.block.multitileentity.MultiTileEntityRegistry.add(Ljava/lang/String;Ljava/lang/String;Lgregapi/block/multitileentity/MultiTileEntityClassContainer;)Lnet/minecraft/item/ItemStack;
    at bloodasp.gregtechextras.Recipes.initRecipes(Recipes.java:98)
    at bloodasp.gregtechextras.GTExtras.onPreLoad(GTExtras.java:149)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
    ... 10 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1089986928 bytes (1039 MB) / 1764229120 bytes (1682 MB) up to 3817865216 bytes (3641 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1557 43 mods loaded, 43 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCH mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCH FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1557-1.7.10.jar) 
    UCH Forge{10.13.4.1557} [Minecraft Forge](forge-1.7.10-10.13.4.1557-1.7.10.jar) 
    UCH appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core](minecraft.jar) 
    UCH Aroma1997Core{1.0.2.16} [Aroma1997Core](Aroma1997Core-1.7.10-1.0.2.16.jar) 
    UCH CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar) 
    UCH Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) 
    UCH NotEnoughItems{1.0.5.118} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
    UCH <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCH adventurebackpack{1.7.10-0.8b} [Adventure Backpack](adventurebackpack-1.7.10-0.8b.jar) 
    UCH gregapi{GT6-MC1710} [Greg-API](gregtech_1.7.10-6.00.59.jar) 
    UCH appliedenergistics2{rv2-stable-10} [Applied Energistics 2](appliedenergistics2-rv2-stable-10.jar) 
    UCH Aroma1997CoreHelper{1.0.2.16} [Aroma1997Core|Helper](Aroma1997Core-1.7.10-1.0.2.16.jar) 
    UCH AromaBackup{0.0.0.5} [AromaBackup](AromaBackup-1.7.10-0.0.0.5.jar) 
    UCH bdlib{1.9.3.107} [BD Lib](bdlib-1.9.3.107-mc1.7.10.jar) 
    UCH ChickenChunks{1.3.4.19} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
    UCH CoFHCore{1.7.10R3.0.3} [CoFH Core](CoFHCore-[1.7.10]3.0.3-303.jar) 
    UCH EnderStorage{1.4.7.37} [EnderStorage](EnderStorage-1.7.10-1.4.7.37-universal.jar) 
    UCH ForgeMultipart{1.2.0.345} [Forge Multipart](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCH ExtraUtilities{1.2.12} [Extra Utilities](extrautilities-1.2.12.jar) 
    UCH IC2{2.2.791-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.791-experimental.jar) 
    UCH Forestry{4.1.1.46} [Forestry for Minecraft](forestry_1.7.10-4.1.1.46.jar) 
    UCH GalacticraftCore{3.0.12} [Galacticraft Core](GalacticraftCore-1.7-3.0.12.375.jar) 
    UCH GalacticraftMars{3.0.12} [Galacticraft Planets](Galacticraft-Planets-1.7-3.0.12.375.jar) 
    UCH gregtech{GT6-MC1710} [GregTech](gregtech_1.7.10-6.00.59.jar) 
    UCH galacticgreg{1.9} [Galactic Greg](GalacticGreg-1.9.jar) 
    UCH gendustry{1.6.2.127} [GenDustry](gendustry-1.6.2.127-mc1.7.10.jar) 
    UCH advgenerators{0.9.18.113} [Advanced Generators](generators-0.9.18.113-mc1.7.10.jar) 
    UCE gtextras{0.3.3} [GTExtras](GTExtras-0.3.3.jar) 
    UCH ImmersiveEngineering{0.6.1} [Immersive Engineering](ImmersiveEngineering-0.6.1.jar) 
    UCH immersiveintegration{0.6.1} [Immersive Integration](immersiveintegration-0.6.1.jar) 
    UCH inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks](InventoryTweaks-1.59-dev-152.jar) 
    UCH NEIAddons{1.12.14.40} [NEI Addons](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCH NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCH NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCH NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCH NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCH NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCH NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCH neiintegration{1.0.13} [NEI Integration](NEIIntegration-MC1.7.10-1.0.13.jar) 
    UCH McMultipart{1.2.0.345} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCH MrTJPCoreMod{1.1.0.31} [MrTJPCore](MrTJPCore-1.1.0.31-universal.jar) 
    UCH ForgeMicroblock{1.2.0.345} [Forge Microblocks](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.200.1062.1004' Renderer: 'AMD Radeon R7 200 Series'
    AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
    CoFHCore: -[1.7.10]3.0.3-303
    List of loaded APIs: 
        \* appliedenergistics2|API (rv2) from appliedenergistics2-rv2-stable-10.jar
        \* BuildCraftAPI|core (1.0) from extrautilities-1.2.12.jar
        \* BuildCraftAPI|tools (1.0) from extrautilities-1.2.12.jar
        \* CoFHAPI (1.7.10R1.0.13B1) from extrautilities-1.2.12.jar
        \* CoFHAPI|block (1.7.10R1.0.13B1) from extrautilities-1.2.12.jar
        \* CoFHAPI|core (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHAPI|energy (1.7.10R1.0.13) from ImmersiveEngineering-0.6.1.jar
        \* CoFHAPI|fluid (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHAPI|inventory (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHAPI|item (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHAPI|modhelpers (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHAPI|tileentity (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHAPI|transport (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHAPI|world (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHLib (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHLib|audio (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHLib|gui (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHLib|gui|container (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHLib|gui|element (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHLib|gui|element|listbox (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHLib|gui|slot (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHLib|inventory (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHLib|render (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHLib|render|particle (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHLib|util (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHLib|util|helpers (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHLib|util|position (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHLib|world (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHLib|world|feature (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* ForestryAPI|apiculture (4.4.1) from forestry_1.7.10-4.1.1.46.jar
        \* ForestryAPI|arboriculture (4.2.1) from forestry_1.7.10-4.1.1.46.jar
        \* ForestryAPI|circuits (3.1.0) from forestry_1.7.10-4.1.1.46.jar
        \* ForestryAPI|core (5.0.0) from forestry_1.7.10-4.1.1.46.jar
        \* ForestryAPI|farming (2.0.0) from forestry_1.7.10-4.1.1.46.jar
        \* ForestryAPI|food (1.1.0) from forestry_1.7.10-4.1.1.46.jar
        \* ForestryAPI|fuels (2.0.1) from forestry_1.7.10-4.1.1.46.jar
        \* ForestryAPI|genetics (4.4.0) from forestry_1.7.10-4.1.1.46.jar
        \* ForestryAPI|hives (4.1.0) from forestry_1.7.10-4.1.1.46.jar
        \* ForestryAPI|lepidopterology (1.3.0) from forestry_1.7.10-4.1.1.46.jar
        \* ForestryAPI|mail (3.0.0) from forestry_1.7.10-4.1.1.46.jar
        \* ForestryAPI|recipes (5.4.0) from forestry_1.7.10-4.1.1.46.jar
        \* ForestryAPI|storage (3.0.0) from forestry_1.7.10-4.1.1.46.jar
        \* ForestryAPI|world (2.1.0) from forestry_1.7.10-4.1.1.46.jar
        \* Galacticraft API (1.0) from GalacticraftCore-1.7-3.0.12.375.jar
        \* gendustryAPI (2.3.0) from gendustry-1.6.2.127-mc1.7.10.jar
        \* IC2API (1.0) from industrialcraft-2-2.2.791-experimental.jar
        \* ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.6.1.jar
        \* RailcraftAPI|crafting (1.0.0) from ImmersiveEngineering-0.6.1.jar

**Comment by Blood-Asp** [comment]
I just tried with GT6.00.60 and everything works fine.
This crash happend when starting, right? or at loading the world? Placing a certain machine? Do you have changed some configs?

**Comment by SirKastros** [comment]
I left the config at default and it crashed at start of Mc

**Comment by ghost** [comment]
Apparently there's problem with 00.59 versiong of GT6 also.
And 00.61, could you tell us how to fix that?

**Comment by Blood-Asp** [comment]
https://www.dropbox.com/s/j8uiyxik588ey8w/GTExtras-0.3.4-test.jar?dl=0 give this a test

**Comment by SirKastros** [comment]
Tested on GT 6 build 61 and build 62 and the game started up fine
